version: '3.8'

services:
  client-db:
    image: postgres:latest
    container_name: inventory-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=inventory-db
    ports:
      - "5433:5432"