services:
  inventory-db:
    image: postgres:latest
    container_name: inventory-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=inventory-db
    ports:
      - "5433:5432"

  inventory-app:
    build: .
    container_name: inventory-app
    environment:
      - DB_URL=jdbc:postgresql://inventory-db:5432/inventory-db
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - inventory-db
    ports:
      - "8081:8080"